// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgmoveRes.proto

package proto;

public final class MsgmoveRes {
  private MsgmoveRes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgmoveResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.msgmoveRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required float time = 1;</code>
     */
    float getTime();

    /**
     * <code>required float dstX = 2;</code>
     */
    boolean hasDstX();
    /**
     * <code>required float dstX = 2;</code>
     */
    float getDstX();

    /**
     * <code>required float dstY = 3;</code>
     */
    boolean hasDstY();
    /**
     * <code>required float dstY = 3;</code>
     */
    float getDstY();
  }
  /**
   * Protobuf type {@code proto.msgmoveRes}
   */
  public static final class msgmoveRes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.msgmoveRes)
      msgmoveResOrBuilder {
    // Use msgmoveRes.newBuilder() to construct.
    private msgmoveRes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private msgmoveRes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final msgmoveRes defaultInstance;
    public static msgmoveRes getDefaultInstance() {
      return defaultInstance;
    }

    public msgmoveRes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private msgmoveRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              time_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              dstX_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              dstY_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.MsgmoveRes.internal_static_proto_msgmoveRes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.MsgmoveRes.internal_static_proto_msgmoveRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.MsgmoveRes.msgmoveRes.class, proto.MsgmoveRes.msgmoveRes.Builder.class);
    }

    public static com.google.protobuf.Parser<msgmoveRes> PARSER =
        new com.google.protobuf.AbstractParser<msgmoveRes>() {
      public msgmoveRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msgmoveRes(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<msgmoveRes> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private float time_;
    /**
     * <code>required float time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float time = 1;</code>
     */
    public float getTime() {
      return time_;
    }

    public static final int DSTX_FIELD_NUMBER = 2;
    private float dstX_;
    /**
     * <code>required float dstX = 2;</code>
     */
    public boolean hasDstX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float dstX = 2;</code>
     */
    public float getDstX() {
      return dstX_;
    }

    public static final int DSTY_FIELD_NUMBER = 3;
    private float dstY_;
    /**
     * <code>required float dstY = 3;</code>
     */
    public boolean hasDstY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float dstY = 3;</code>
     */
    public float getDstY() {
      return dstY_;
    }

    private void initFields() {
      time_ = 0F;
      dstX_ = 0F;
      dstY_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDstX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDstY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, dstX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, dstY_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, dstX_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, dstY_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.MsgmoveRes.msgmoveRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.MsgmoveRes.msgmoveRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.MsgmoveRes.msgmoveRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.MsgmoveRes.msgmoveRes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.msgmoveRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.msgmoveRes)
        proto.MsgmoveRes.msgmoveResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.MsgmoveRes.internal_static_proto_msgmoveRes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.MsgmoveRes.internal_static_proto_msgmoveRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.MsgmoveRes.msgmoveRes.class, proto.MsgmoveRes.msgmoveRes.Builder.class);
      }

      // Construct using proto.MsgmoveRes.msgmoveRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        dstX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        dstY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.MsgmoveRes.internal_static_proto_msgmoveRes_descriptor;
      }

      public proto.MsgmoveRes.msgmoveRes getDefaultInstanceForType() {
        return proto.MsgmoveRes.msgmoveRes.getDefaultInstance();
      }

      public proto.MsgmoveRes.msgmoveRes build() {
        proto.MsgmoveRes.msgmoveRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.MsgmoveRes.msgmoveRes buildPartial() {
        proto.MsgmoveRes.msgmoveRes result = new proto.MsgmoveRes.msgmoveRes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dstX_ = dstX_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dstY_ = dstY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.MsgmoveRes.msgmoveRes) {
          return mergeFrom((proto.MsgmoveRes.msgmoveRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.MsgmoveRes.msgmoveRes other) {
        if (other == proto.MsgmoveRes.msgmoveRes.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDstX()) {
          setDstX(other.getDstX());
        }
        if (other.hasDstY()) {
          setDstY(other.getDstY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        if (!hasDstX()) {
          
          return false;
        }
        if (!hasDstY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.MsgmoveRes.msgmoveRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.MsgmoveRes.msgmoveRes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float time_ ;
      /**
       * <code>required float time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float time = 1;</code>
       */
      public float getTime() {
        return time_;
      }
      /**
       * <code>required float time = 1;</code>
       */
      public Builder setTime(float value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0F;
        onChanged();
        return this;
      }

      private float dstX_ ;
      /**
       * <code>required float dstX = 2;</code>
       */
      public boolean hasDstX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float dstX = 2;</code>
       */
      public float getDstX() {
        return dstX_;
      }
      /**
       * <code>required float dstX = 2;</code>
       */
      public Builder setDstX(float value) {
        bitField0_ |= 0x00000002;
        dstX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float dstX = 2;</code>
       */
      public Builder clearDstX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dstX_ = 0F;
        onChanged();
        return this;
      }

      private float dstY_ ;
      /**
       * <code>required float dstY = 3;</code>
       */
      public boolean hasDstY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float dstY = 3;</code>
       */
      public float getDstY() {
        return dstY_;
      }
      /**
       * <code>required float dstY = 3;</code>
       */
      public Builder setDstY(float value) {
        bitField0_ |= 0x00000004;
        dstY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float dstY = 3;</code>
       */
      public Builder clearDstY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dstY_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.msgmoveRes)
    }

    static {
      defaultInstance = new msgmoveRes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.msgmoveRes)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_msgmoveRes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_msgmoveRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020msgmoveRes.proto\022\005proto\"6\n\nmsgmoveRes\022" +
      "\014\n\004time\030\001 \002(\002\022\014\n\004dstX\030\002 \002(\002\022\014\n\004dstY\030\003 \002(" +
      "\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_msgmoveRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_msgmoveRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_msgmoveRes_descriptor,
        new java.lang.String[] { "Time", "DstX", "DstY", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
