// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgmoveRes.proto

#ifndef PROTOBUF_msgmoveRes_2eproto__INCLUDED
#define PROTOBUF_msgmoveRes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msgmoveRes_2eproto();
void protobuf_AssignDesc_msgmoveRes_2eproto();
void protobuf_ShutdownFile_msgmoveRes_2eproto();

class msgmoveRes;

// ===================================================================

class msgmoveRes : public ::google::protobuf::Message {
 public:
  msgmoveRes();
  virtual ~msgmoveRes();

  msgmoveRes(const msgmoveRes& from);

  inline msgmoveRes& operator=(const msgmoveRes& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const msgmoveRes& default_instance();

  void Swap(msgmoveRes* other);

  // implements Message ----------------------------------------------

  msgmoveRes* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const msgmoveRes& from);
  void MergeFrom(const msgmoveRes& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline float time() const;
  inline void set_time(float value);

  // required float dstX = 2;
  inline bool has_dstx() const;
  inline void clear_dstx();
  static const int kDstXFieldNumber = 2;
  inline float dstx() const;
  inline void set_dstx(float value);

  // required float dstY = 3;
  inline bool has_dsty() const;
  inline void clear_dsty();
  static const int kDstYFieldNumber = 3;
  inline float dsty() const;
  inline void set_dsty(float value);

  // @@protoc_insertion_point(class_scope:proto.msgmoveRes)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_dstx();
  inline void clear_has_dstx();
  inline void set_has_dsty();
  inline void clear_has_dsty();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float time_;
  float dstx_;
  float dsty_;
  friend void  protobuf_AddDesc_msgmoveRes_2eproto();
  friend void protobuf_AssignDesc_msgmoveRes_2eproto();
  friend void protobuf_ShutdownFile_msgmoveRes_2eproto();

  void InitAsDefaultInstance();
  static msgmoveRes* default_instance_;
};
// ===================================================================


// ===================================================================

// msgmoveRes

// required float time = 1;
inline bool msgmoveRes::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void msgmoveRes::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void msgmoveRes::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void msgmoveRes::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline float msgmoveRes::time() const {
  // @@protoc_insertion_point(field_get:proto.msgmoveRes.time)
  return time_;
}
inline void msgmoveRes::set_time(float value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:proto.msgmoveRes.time)
}

// required float dstX = 2;
inline bool msgmoveRes::has_dstx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void msgmoveRes::set_has_dstx() {
  _has_bits_[0] |= 0x00000002u;
}
inline void msgmoveRes::clear_has_dstx() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void msgmoveRes::clear_dstx() {
  dstx_ = 0;
  clear_has_dstx();
}
inline float msgmoveRes::dstx() const {
  // @@protoc_insertion_point(field_get:proto.msgmoveRes.dstX)
  return dstx_;
}
inline void msgmoveRes::set_dstx(float value) {
  set_has_dstx();
  dstx_ = value;
  // @@protoc_insertion_point(field_set:proto.msgmoveRes.dstX)
}

// required float dstY = 3;
inline bool msgmoveRes::has_dsty() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void msgmoveRes::set_has_dsty() {
  _has_bits_[0] |= 0x00000004u;
}
inline void msgmoveRes::clear_has_dsty() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void msgmoveRes::clear_dsty() {
  dsty_ = 0;
  clear_has_dsty();
}
inline float msgmoveRes::dsty() const {
  // @@protoc_insertion_point(field_get:proto.msgmoveRes.dstY)
  return dsty_;
}
inline void msgmoveRes::set_dsty(float value) {
  set_has_dsty();
  dsty_ = value;
  // @@protoc_insertion_point(field_set:proto.msgmoveRes.dstY)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msgmoveRes_2eproto__INCLUDED
