// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgmoveRes.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgmoveRes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {

namespace {

const ::google::protobuf::Descriptor* msgmoveRes_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  msgmoveRes_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgmoveRes_2eproto() {
  protobuf_AddDesc_msgmoveRes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgmoveRes.proto");
  GOOGLE_CHECK(file != NULL);
  msgmoveRes_descriptor_ = file->message_type(0);
  static const int msgmoveRes_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msgmoveRes, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msgmoveRes, dstx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msgmoveRes, dsty_),
  };
  msgmoveRes_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      msgmoveRes_descriptor_,
      msgmoveRes::default_instance_,
      msgmoveRes_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msgmoveRes, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(msgmoveRes, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(msgmoveRes));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgmoveRes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    msgmoveRes_descriptor_, &msgmoveRes::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msgmoveRes_2eproto() {
  delete msgmoveRes::default_instance_;
  delete msgmoveRes_reflection_;
}

void protobuf_AddDesc_msgmoveRes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020msgmoveRes.proto\022\005proto\"6\n\nmsgmoveRes\022"
    "\014\n\004time\030\001 \002(\002\022\014\n\004dstX\030\002 \002(\002\022\014\n\004dstY\030\003 \002("
    "\002", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgmoveRes.proto", &protobuf_RegisterTypes);
  msgmoveRes::default_instance_ = new msgmoveRes();
  msgmoveRes::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgmoveRes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgmoveRes_2eproto {
  StaticDescriptorInitializer_msgmoveRes_2eproto() {
    protobuf_AddDesc_msgmoveRes_2eproto();
  }
} static_descriptor_initializer_msgmoveRes_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int msgmoveRes::kTimeFieldNumber;
const int msgmoveRes::kDstXFieldNumber;
const int msgmoveRes::kDstYFieldNumber;
#endif  // !_MSC_VER

msgmoveRes::msgmoveRes()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.msgmoveRes)
}

void msgmoveRes::InitAsDefaultInstance() {
}

msgmoveRes::msgmoveRes(const msgmoveRes& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:proto.msgmoveRes)
}

void msgmoveRes::SharedCtor() {
  _cached_size_ = 0;
  time_ = 0;
  dstx_ = 0;
  dsty_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

msgmoveRes::~msgmoveRes() {
  // @@protoc_insertion_point(destructor:proto.msgmoveRes)
  SharedDtor();
}

void msgmoveRes::SharedDtor() {
  if (this != default_instance_) {
  }
}

void msgmoveRes::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* msgmoveRes::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return msgmoveRes_descriptor_;
}

const msgmoveRes& msgmoveRes::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgmoveRes_2eproto();
  return *default_instance_;
}

msgmoveRes* msgmoveRes::default_instance_ = NULL;

msgmoveRes* msgmoveRes::New() const {
  return new msgmoveRes;
}

void msgmoveRes::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<msgmoveRes*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(time_, dsty_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool msgmoveRes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.msgmoveRes)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float time = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_dstX;
        break;
      }

      // required float dstX = 2;
      case 2: {
        if (tag == 21) {
         parse_dstX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dstx_)));
          set_has_dstx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_dstY;
        break;
      }

      // required float dstY = 3;
      case 3: {
        if (tag == 29) {
         parse_dstY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &dsty_)));
          set_has_dsty();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.msgmoveRes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.msgmoveRes)
  return false;
#undef DO_
}

void msgmoveRes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.msgmoveRes)
  // required float time = 1;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->time(), output);
  }

  // required float dstX = 2;
  if (has_dstx()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->dstx(), output);
  }

  // required float dstY = 3;
  if (has_dsty()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->dsty(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.msgmoveRes)
}

::google::protobuf::uint8* msgmoveRes::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.msgmoveRes)
  // required float time = 1;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->time(), target);
  }

  // required float dstX = 2;
  if (has_dstx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->dstx(), target);
  }

  // required float dstY = 3;
  if (has_dsty()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->dsty(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.msgmoveRes)
  return target;
}

int msgmoveRes::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float time = 1;
    if (has_time()) {
      total_size += 1 + 4;
    }

    // required float dstX = 2;
    if (has_dstx()) {
      total_size += 1 + 4;
    }

    // required float dstY = 3;
    if (has_dsty()) {
      total_size += 1 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void msgmoveRes::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const msgmoveRes* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const msgmoveRes*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void msgmoveRes::MergeFrom(const msgmoveRes& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_dstx()) {
      set_dstx(from.dstx());
    }
    if (from.has_dsty()) {
      set_dsty(from.dsty());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void msgmoveRes::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void msgmoveRes::CopyFrom(const msgmoveRes& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool msgmoveRes::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void msgmoveRes::Swap(msgmoveRes* other) {
  if (other != this) {
    std::swap(time_, other->time_);
    std::swap(dstx_, other->dstx_);
    std::swap(dsty_, other->dsty_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata msgmoveRes::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = msgmoveRes_descriptor_;
  metadata.reflection = msgmoveRes_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)
